object Versions {
    const val coreKtx = "1.9.0"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val navigationCompose = "2.7.3"
    const val lifecycleRuntimeKtx = "2.6.2"
    const val activityCompose = "1.7.2"
    const val compose = "2023.03.00"
    const val jUnit = "4.13.2"
    const val extJunit = "1.1.5"
    const val core = "3.5.1"
    const val lifecycleViewModel = "2.6.2"
    const val hilt = "2.44"
    const val hiltCompiler = "1.0.0"
    const val hiltNavigationCopose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutines =  "1.7.3"
}